import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torch.utils.data import DataLoader, random_split, Dataset, WeightedRandomSampler
import joblib
import warnings

from Data import Field

class StratDataset(Dataset):

    def __init__(self, X, y):
        self.X = torch.from_numpy(X.values).float()
        self.y = torch.from_numpy(y[Field.STRAT].values).long()

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class IntervalNeuralNetwork(nn.Module):

    def __init__(self, num_classes : int):
        super().__init__()
        self.num_classes = num_classes

        self.linear0 = nn.Linear(3, 2048)
        self.linear1 = nn.Linear(2048, 1024)
        self.linear2 = nn.Linear(1024, 512)
        self.linear3 = nn.Linear(512, 256)
        self.linear4 = nn.Linear(256, self.num_classes)

        self.dropout = nn.Dropout(p=.2)

    def forward(self, X):
        X = F.relu(self.linear0(X))
        X = self.dropout(X)
        X = F.relu(self.linear1(X))
        X = self.dropout(X)
        X = F.relu(self.linear2(X))
        X = self.dropout(X)
        X = F.relu(self.linear3(X))
        X = self.linear4(X)

        return X

class SignedDistanceInterpolatedLoss(nn.Module):

    def __init__(self, num_classes : int, r1 = 1e-5, r2 = 1.0):
        super().__init__()
        self.num_classes = num_classes
        self.r1 = r1
        self.r2 = r2

        self.elevation_scaler = joblib.load('nn/elevation.scl')

    def forward(self, y_pred, y, spatial, device):

        member_weight = torch.where(y >= 0,
                                    torch.tensor(1, dtype=torch.float32, device=device),
                                    torch.tensor(0.5, dtype=torch.float32, device=device))

        """Clamp values to min of -6 to imitate how nan/inf values are handled for MSE loss"""
        loss = F.mse_loss(torch.clamp(y_pred, min=-6.0), y, reduction='none')
        loss = member_weight * loss

        if spatial is None:
            return loss.mean()

        if not spatial.requires_grad:
            spatial.requires_grad_(True)

        """Laplacian smoothing"""
        gradients = torch.autograd.grad(
            outputs=torch.exp(y_pred) - 1,
            inputs=spatial,
            grad_outputs=torch.ones_like(y_pred),
            create_graph=True,
            retain_graph=True
        )[0]

        hessian = []
        for idx in range(1,3):
            second_derivative = torch.autograd.grad(
                outputs=gradients[:, idx].sum(),
                inputs=spatial,
                create_graph=True,
                retain_graph=True
            )[0][:, idx]

            hessian.append(second_derivative)

        hessian = torch.stack(hessian, dim=1)

        smoothness_loss = torch.mean(hessian ** 2)

        """Difference between the distances to the nearest formation as generated by the largest 2 values of y_pred"""
        boundary_loss, _ = torch.topk(y_pred, k=2, dim=-1)
        boundary_loss = torch.abs(boundary_loss.sum(dim=-1)).mean()

        return loss.mean() + self.r1 * smoothness_loss + self.r2 * boundary_loss

def train_model_interpolated(data, max_epochs=15, lr=1e-3, save_path='nn'):
    train_loader = data[0]
    test_loader = data[1]
    sdf = data[2]
    encoder = data[3]

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    model = IntervalNeuralNetwork(len(encoder.classes_))

    model.to(device)

    optimizer = Adam(model.parameters(), lr=lr)
    loss_func = SignedDistanceInterpolatedLoss(len(encoder.classes_))

    best_loss = np.inf

    for epoch in range(max_epochs):
        print(f'Epoch {epoch+1}')

        model.train()

        train_loss = 0
        for X, y in train_loader:
            X = X.to(device)
            y = y.to(device)

            X.requires_grad_(True)

            output = model(X)

            loss = loss_func(output, y, X, device)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        print(f'Train Loss {train_loss / len(train_loader)}')

        model.eval()

        test_loss = 0
        with torch.no_grad():
            for X, y in test_loader:
                X = X.to(device)
                y = y.to(device)

                output = model(X)

                loss = loss_func(output, y, None, device)

                test_loss += loss.item()

        print(f'Test Loss {test_loss / len(test_loader)}')

        if test_loss < best_loss:
            best_loss = test_loss

            torch.save(model.state_dict(), f'{save_path}/sdf.pth')

            config = {
                'output_size' : len(encoder.classes_),
                'best_loss' : best_loss,
                'epoch' : epoch
            }
            joblib.dump(config, f'{save_path}/config.txt')

def test_model(utme, utmn, elevation, path='nn'):
    warnings.filterwarnings('ignore')

    config = joblib.load(f'{path}/config.txt')

    model = IntervalNeuralNetwork(config['output_size'])
    state_dict = torch.load(f'{path}/sdf.pth')
    model.load_state_dict(state_dict)
    model.eval()

    utme_scaler = joblib.load(f'{path}/utme.scl')
    utmn_scaler = joblib.load(f'{path}/utmn.scl')
    elevation_scaler = joblib.load(f'{path}/elevation.scl')

    utme = utme_scaler.transform([[utme]])[0][0]
    utmn = utmn_scaler.transform([[utmn]])[0][0]
    elevation = elevation_scaler.transform([[elevation]])[0][0]

    X = torch.tensor([elevation, utme, utmn]).float().unsqueeze(0)

    with torch.no_grad():
        output = model(X)

    return output

def get_borehole_accuracy(df, path):
    warnings.filterwarnings('ignore')

    config = joblib.load(f'{path}/config.txt')

    model = IntervalNeuralNetwork(config['output_size'])
    state_dict = torch.load(f'{path}/sdf.pth')
    model.load_state_dict(state_dict)
    model.eval()

    utme_scaler = joblib.load(f'{path}/utme.scl')
    utmn_scaler = joblib.load(f'{path}/utmn.scl')
    elevation_scaler = joblib.load(f'{path}/elevation.scl')

    encoder = joblib.load(f'{path}/strat.enc')

    total = np.zeros(shape=config['output_size'], dtype=int)
    correct = np.zeros(shape=config['output_size'], dtype=int)

    for _, row in df.iterrows():

        """Offset elevations by 0.5 to get the central reading of each section"""
        size = int(row[Field.ELEVATION_TOP]) - int(row[Field.ELEVATION_BOT])

        elevations = np.array(range(int(row[Field.ELEVATION_BOT]), int(row[Field.ELEVATION_TOP]))) + 0.5 + row[Field.ELEVATION_BOT]
        utme = np.full(size, row[Field.UTME])
        utmn = np.full(size, row[Field.UTMN])

        elevations = elevation_scaler.transform(elevations.reshape(-1, 1)).reshape(size)
        utme = utme_scaler.transform(utme.reshape(-1, 1)).reshape(size)
        utmn = utmn_scaler.transform(utmn.reshape(-1, 1)).reshape(size)

        X = torch.tensor([elevations, utme, utmn], dtype=torch.float32).reshape(size, 3)
        y = row['strat_top']

        total[y] += int(row[Field.ELEVATION_TOP] - row[Field.ELEVATION_BOT])

        with torch.no_grad():
            output = model(X)

        for val in output:
            pred = np.argmax(val)

            if pred == y:
                correct[pred] += 1

    return correct, total